### ISSUE TITLE
asgi_redis silently fails to send with redis version < 2.6

### ISSUE THREAD

**Issue by wynbennett** [django/asgi_redis#14]
If someone is running a redis version less than 2.6 then asgi_redis will fail silently in the send() call.  

In the exception catch starting here https://github.com/django/asgi_redis/blob/master/asgi_redis/core.py#L107
There is no case for if a different error other than 'full' occurs.  Namely if "unknown command 'EVALSHA'" occurs which will happen for redis versions < 2.6.  

This can cause users applications to fail to respond for unknown reasons as both the workers and daphne will connect to redis just fine but no information will be passed between them due to this failure.

Considering the default version of redis in EPEL is 2.4 this could cause many people to tear their hair out wondering what is going on.

**Comment by maikhoepfel** [comment]
I can reproduce the issue and will attempt to provide a fix this week.

**Comment by maikhoepfel** [comment]
I posted a potential fix in https://github.com/maikhoepfel/asgi_redis/pull/1. I'm happy to add a proper test against Redis 2.4 if we decide we want to run different Redis versions as part of the Travis test suite.

**Comment by andrewgodwin** [comment]
Fixed by #15.
