### ISSUE TITLE
Configurable tcp socket keepalive on Redis connection - improved resiliency

### ISSUE THREAD

**Issue by edevil** [django/asgi_redis#26]
Current PaaS solutions have very aggressive pruning of idle TCP connections, which affects ASGI workers since they maintain open connections to Redis and are left waiting for messages indefinitely, not sending anything. I see two solutions for this problem:

1. A hearbeat protocol that would send "PING" commands periodically to the Redis server.
1. Ability to configure the socket_keepalive_options of the ```redis-py``` connection. It is not possible to provide a value for this via a connection URL.

**Comment by edevil** [comment]
Upon further investigation the asgi_redis module is using 5s timeouts on BLPOP messages, which should keep the connection healthy, however I've seen cases where the connection is dropped and the BLPOP response is never received. In this case the worker would wait forever. Using the ```socket_timeout``` option to the redis-py connection solves this issue, so I don't know if anything else is needed...

**Comment by andrewgodwin** [comment]
Yes, the pops are refreshed quite often, but the underlying socket connection is held open, and that might be what's dying. How did you add `socket_timeout` - is it something we should support?

**Comment by edevil** [comment]
In the layer config, I used a connection URL to configure a host. Here we can pass query parameters such as ```socket_timeout=10``` to redis-py. I don't think anything else needs to be done since this is backend specific.

**Comment by andrewgodwin** [comment]
Alright, lovely! Hopefully someone else can find that info useful too.

**Comment by edevil** [comment]
I've been running more tests and, although the socket_timeout solves the issue of the worker waiting forever, it seems that being able to configure the socket_keepalive_options parameter of redis-py would be helpful. Otherwise when an idle connection is dropped there's still a noticeable lag while waiting for the timeout on the next call, whereas if the dropped connection was detected earlier the experience would be better.

**Comment by andrewgodwin** [comment]
Alright - do you want to open a new ticket with the details of what kind of configuration options would be useful? I have some time tomorrow I can use to work those in (it would be nice to expose socket_timeout more directly too, potentially, and document it)
