### ISSUE TITLE
Performance question: while True: lpopmany ?

### ISSUE THREAD

**Issue by NotSqrt** [django/asgi_redis#27]
Hi !

I've been playing with channels and asgi_redis, and what I see in `redis-cli monitor` is a huge lot of calls to the lua script in `lua_lpopmany`, which is called in a `while True` loop : ~100 calls per second.

Do I need to be concerned about performance/load issues when running redis on a very small VM because of the high amount of commands being run ?

I imagine there might be a way to use redis pub/sub features somehow to implement this differently ? https://redis.io/commands#pubsub

Thanks !

**Comment by proofit404** [comment]
Turning redis connection into pub/sub mode will disable another commands execution. You can't run `LPUSH` while you are in the pub/sub mode. For example, exactly the same reason lays in the way celery implements redis broker.

For the speed I can confirm it is the fastest layer implementation right now. It gives 0.010s latency at my very old laptop.

**Comment by andrewgodwin** [comment]
To expand on this - ASGI backends have two modes, a blocking mode that waits for changes (this is what the Django worker uses) and a nonblocking mode that fast-polls like you see, which is what Daphne uses.

The reason for this is that the list of channels it has to listen on changes as new connections come in, so any delay or blocking poll would mean new connections having significant latency in the handshake process.
