### ISSUE TITLE
Expose more redis-py configuration options

### ISSUE THREAD

**Issue by edevil** [django/asgi_redis#28]
There are a number of redis-py configuration options that are useful and should be exposed by asgi_redis. Some of them can already be configured via a connection URL, but there are others which cannot.

- ```socket_connect_timeout```: Integer. Number of seconds to wait for the connection to be established.
- ```socket_timeout```: Integer. Number of seconds to wait for a response to a Redis command. Has to be higher than 5 otherwise the ```BLPOP``` operation used by the workers will always timeout.
- ```socket_keepalive```: Boolean. Wether to turn on TCP keepalives.
- ```socket_keepalive_options```: Dict with values used to configure the keepalive mechanism. It is supposed to use as keys the socket options (socket.TCP_KEEPIDLE, socket.TCP_KEEPCNT, socket.TCP_KEEPINTVL) however, in MacOS, the socket.TCP_KEEPIDLE constant does not exist. According to https://opensource.apple.com/source/xnu/xnu-2422.115.4/bsd/netinet/tcp.h the constant that we need is TCP_KEEPALIVE, which has a value of 0x10, so in theory we can pass that value as key in the dict to set the correct value. But maybe it's better to hide this mess from users.

Related to #26.

**Comment by andrewgodwin** [comment]
Made all four of these configurable via the config dictionary, with a check for timeout being long enough.

**Comment by edevil** [comment]
Thanks!
