### ISSUE TITLE
Questions about license

### ISSUE THREAD

**Issue by Ya2s** [django/asgi_redis#29]
Hello,

I am sorry, I have already asked a same question about Channels but I have always a doubt for asgi_redis :

Have I to mentione the authors name in my website (using asgi_redis) ?
Have I to mentione something else ?

Thank you !

**Comment by andrewgodwin** [comment]
The answer is the same as the one for Channels as the license is the same. You can examine the license to check this. I am not a lawyer, however; you may want to ask one if you are still unsure.
