### ISSUE TITLE
Support for redis-sentinel

### ISSUE THREAD

**Issue by ZuSe** [django/asgi_redis#30]
Hi folks,

are there any plans to support besides single host and clustered deployment a sentinel setup?
Especially for deployments where redis has to be reliable and highly available the sentinel deployment would be nice to have. 

Maybe https://github.com/dealertrack/celery-redis-sentinel helps as a starting point?

**Comment by andrewgodwin** [comment]
We already have a subclass of asgi_redis at work that uses sentinel, so it's definitely possible, and would probably be a nice thing to have.

**Comment by ZuSe** [comment]
Can you share it or do we need to reimplement?

**Comment by andrewgodwin** [comment]
I'll look into it but I can't make any promises.

**Comment by ZuSe** [comment]
Hey andrew,

do you have any news on this issue?
Just do know if it's open to be done

**Comment by andrewgodwin** [comment]
I haven't had time to look into it yet. If you wish to implement it, be my guest.

**Comment by bgreenberg-eb** [comment]
@ZuSe Have a look at `RedisSentinelChannelLayer`. This [update](https://github.com/django/asgi_redis/pull/43``) expanded its functionality quite a bit.

**Comment by andrewgodwin** [comment]
Yup, this is now fixed! There's some notes in the README.

**Comment by lvnar** [comment]
> @ZuSe Have a look at `RedisSentinelChannelLayer`. This [update](https://github.com/django/asgi_redis/pull/43%60%60) expanded its functionality quite a bit.

The link is broken. I can't figure out the way @andrewgodwin marked it as fixed. Any help?

**Comment by carltongibson** [comment]
Both links now updated.
