### ISSUE TITLE
Question about redis being full

### ISSUE THREAD

**Issue by LadaBr** [django/asgi_redis#31]
I'm getting this error after a while when there is like 40 users connected to the server. I'm running 10 workers as separated processes and I'm using django, channels, daphne.

What could I do wrong? Is there some kind of leak or why is there so many messages in queue? Every user sends hearthbeat every 2 seconds and then there are some random messages, for example chat messages and I find it weird. Why is there 2500-4200 keys in redis-cli?

It isn't even lagging. It just becomes full and then every user has to reconnect.

> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/worker.py", line 119, in run
>     consumer(message, **kwargs)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 64, in inner
>     return func(message, *args, **kwargs)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 127, in inner
>     "full __wait__ channel for socket %s" % message.reply_channel.name
> asgiref.base_layer.BaseChannelLayer.ChannelFull: Cannot add unordered message to already full __wait__ channel for socket websocket.send!XAVTijfEWuAm
> 2017-03-13 16:57:18,574 - ERROR - worker - Error processing message with consumer chat.consumers.ws_message:
> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/asgi_redis/core.py", line 121, in send
>     client=connection,
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 2694, in __call__
>     return client.evalsha(self.sha, len(keys), *args)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 1944, in evalsha
>     return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 573, in execute_command
>     return self.parse_response(connection, command_name, **options)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
>     response = connection.read_response()
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/connection.py", line 582, in read_response
>     raise response
> redis.exceptions.ResponseError: full
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 123, in inner
>     message.channel_layer.send(wait_channel, message.content)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/asgi_redis/core.py", line 126, in send
>     raise self.ChannelFull
> asgiref.base_layer.BaseChannelLayer.ChannelFull
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/worker.py", line 119, in run
>     consumer(message, **kwargs)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 64, in inner
>     return func(message, *args, **kwargs)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 127, in inner
>     "full __wait__ channel for socket %s" % message.reply_channel.name
> asgiref.base_layer.BaseChannelLayer.ChannelFull: Cannot add unordered message to already full __wait__ channel for socket websocket.send!XAVTijfEWuAm
> 2017-03-13 16:57:32,573 - ERROR - worker - Error processing message with consumer chat.consumers.ws_message:
> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/asgi_redis/core.py", line 121, in send
>     client=connection,
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 2694, in __call__
>     return client.evalsha(self.sha, len(keys), *args)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 1944, in evalsha
>     return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 573, in execute_command
>     return self.parse_response(connection, command_name, **options)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
>     response = connection.read_response()
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/connection.py", line 582, in read_response
>     raise response
> redis.exceptions.ResponseError: full
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 123, in inner
>     message.channel_layer.send(wait_channel, message.content)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/asgi_redis/core.py", line 126, in send
>     raise self.ChannelFull
> asgiref.base_layer.BaseChannelLayer.ChannelFull
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/worker.py", line 119, in run
>     consumer(message, **kwargs)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 64, in inner
>     return func(message, *args, **kwargs)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 127, in inner
>     "full __wait__ channel for socket %s" % message.reply_channel.name
> asgiref.base_layer.BaseChannelLayer.ChannelFull: Cannot add unordered message to already full __wait__ channel for socket websocket.send!XAVTijfEWuAm
> 
> > Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/worker.py", line 119, in run
>     consumer(message, **kwargs)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 64, in inner
>     return func(message, *args, **kwargs)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 127, in inner
>     "full __wait__ channel for socket %s" % message.reply_channel.name
> asgiref.base_layer.BaseChannelLayer.ChannelFull: Cannot add unordered message to already full __wait__ channel for socket websocket.send!XAVTijfEWuAm
> 2017-03-13 16:57:18,574 - ERROR - worker - Error processing message with consumer chat.consumers.ws_message:
> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/asgi_redis/core.py", line 121, in send
>     client=connection,
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 2694, in __call__
>     return client.evalsha(self.sha, len(keys), *args)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 1944, in evalsha
>     return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 573, in execute_command
>     return self.parse_response(connection, command_name, **options)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
>     response = connection.read_response()
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/connection.py", line 582, in read_response
>     raise response
> redis.exceptions.ResponseError: full
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 123, in inner
>     message.channel_layer.send(wait_channel, message.content)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/asgi_redis/core.py", line 126, in send
>     raise self.ChannelFull
> asgiref.base_layer.BaseChannelLayer.ChannelFull
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/worker.py", line 119, in run
>     consumer(message, **kwargs)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 64, in inner
>     return func(message, *args, **kwargs)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 127, in inner
>     "full __wait__ channel for socket %s" % message.reply_channel.name
> asgiref.base_layer.BaseChannelLayer.ChannelFull: Cannot add unordered message to already full __wait__ channel for socket websocket.send!XAVTijfEWuAm
> 2017-03-13 16:57:32,573 - ERROR - worker - Error processing message with consumer chat.consumers.ws_message:
> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/asgi_redis/core.py", line 121, in send
>     client=connection,
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 2694, in __call__
>     return client.evalsha(self.sha, len(keys), *args)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 1944, in evalsha
>     return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 573, in execute_command
>     return self.parse_response(connection, command_name, **options)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
>     response = connection.read_response()
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/connection.py", line 582, in read_response
>     raise response
> redis.exceptions.ResponseError: full
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 123, in inner
>     message.channel_layer.send(wait_channel, message.content)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/asgi_redis/core.py", line 126, in send
>     raise self.ChannelFull
> asgiref.base_layer.BaseChannelLayer.ChannelFull
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/worker.py", line 119, in run
>     consumer(message, **kwargs)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 64, in inner
>     return func(message, *args, **kwargs)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/sessions.py", line 127, in inner
>     "full __wait__ channel for socket %s" % message.reply_channel.name
> asgiref.base_layer.BaseChannelLayer.ChannelFull: Cannot add unordered message to already full __wait__ channel for socket websocket.send!XAVTijfEWuAm

**Comment by andrewgodwin** [comment]
It looks like you have `enforce_ordering` turned on for one or more consumers - which are they, and is it possible to provide code samples? It looks like you might have run into a bug that has been fixed but not yet released (#532)

**Comment by LadaBr** [comment]
```
@enforce_ordering
@channel_session
def ws_connect(message):
    check_online_users()
    headers = message.content['headers']  
    header_dict = parse_header(headers) 
    if 'cookie' not in header_dict:
        message.reply_channel.send({"close": True})
        return
    session_id = find_cookie(header_dict['cookie'],'sessionid')
    
    if session_id is None:
        message.reply_channel.send({"close": True})
        return

    user_id = get_session_user_id(session_id)
    if user_id is None:
        message.reply_channel.send({"close": True})
        return

    group_name = message.content['path'].rsplit('/', 1)[-1].replace(" ", ".")
    message.channel_session['main_room'] = group_name
    message.channel_session['user_id'] = user_id
    getuser = user.objects.get(user_id=message.channel_session['user_id'])
    user_update(message.channel_session['user_id'])

    try:
        _user = chat_session.objects.get(user=getuser, group_name=group_name, user_id=user_id)
        message.reply_channel.send({"close": True})
    except chat_session.DoesNotExist:
        chat_session(user=getuser, group_name=group_name, user_id=user_id, reply_channel=message.reply_channel).save()
        message.reply_channel.send({"accept": True})
        Group(group_name).add(message.reply_channel)
```

`@enforce_ordering
@channel_session
def ws_message(message):

    

    #group_name = group_prefix+"%s" % message.channel_session['room']

    user_update(message.channel_session['user_id'])
    check_online_users()


    

    msg = json.loads(message.content['text'])


    if 'ping' in msg:
        message.reply_channel.send({
            'text': "1",
        })
        return

    try:
        group_name = msg['room'].replace(' ', '.')
    except KeyError:
        return
    
    
    

    


    if 'cmd' in msg:
        
        if msg['cmd'] == 'join':
            mm_enabled = enabled_stuff.objects.get(name="matchmaking").state
            if not mm_enabled:
                message.reply_channel.send({"text": "Matchmaking is currently not available." })
                return
            getUser = user.objects.get(user_id=message.channel_session['user_id'])
            found = False
            active_matches = matches.objects.filter(match_end__isnull=True, match_start__isnull=False)
            playing = False
            for match in active_matches:
                try:
                    user_playing = matchplayers.objects.get(match_id=match,user=getUser)
                    playing = True
                    message.reply_channel.send({"text": "playing" })
                    return
                except:
                    pass


            for _game_type in game_types:
                if _game_type.name == group_name[0:group_name.rfind('-')]:
                    found = True
                    break
            if getUser.last_ban is not None and found:
                if getUser.last_ban > timezone.now():
                    timestamp = (getUser.last_ban - timezone.now())
                    epoch = int(timestamp.total_seconds() * 1000) 
                    message.reply_channel.send({"text": json.dumps({"banned": epoch}, cls=DjangoJSONEncoder)})
                    return
            Group(group_name).add(message.reply_channel)
            try:
                chat_session.objects.get(user_id=message.channel_session['user_id'],group_name=group_name)
            except:
                for d in game_types:
                    if d.name == msg['room'][0:msg['room'].rfind('-')]:
                        if d.team:
                            try:
                                leader = teams.objects.get(leader=message.channel_session['user_id'])
                            except:
                                message.reply_channel.send({"text": "no leader" })
                                return
                t = chat_session(user=getUser, group_name=group_name, user_id=message.channel_session['user_id'], reply_channel=message.reply_channel)
                t.save()
            #Group(msg['room']).send({
            #    'text': json.dumps({
            #        "hello":"world",
            #    }),
            #})
            
        elif msg['cmd'] == 'leave':
            message.reply_channel.send({"text": "left" })
            Group(group_name).discard(message.reply_channel)
            try:
                chat_session.objects.get(group_name=group_name, user_id=message.channel_session['user_id']).delete()
            except chat_session.DoesNotExist:
                pass

        #message.reply_channel.send({
        #    'text': json.dumps({
        #        'room': msg['room'],
        #        'cmd': msg['cmd'],
        #        'callback': 1
        #    })
        #})

        elif msg['cmd'] == 'send':

            if 'message' in msg:
                user_profile = getSteamProfile(message.channel_session['user_id'])
                Group(group_name).send({
                    'text': json.dumps({
                        'room': group_name.replace(" ","."),
                        'time': time.time(),
                        'message': msg['message'],
                        'nickname': user_profile['response']['players'][0]['personaname'],
                        'avatar': user_profile['response']['players'][0]['avatar'],
                        'user_id': message.channel_session['user_id'],
                        #'users_online': json.dumps(users_in_group(group_prefix+"%s" % message.channel_session['room']), cls=DjangoJSONEncoder),
                    }),
                })

        elif msg['cmd'] == 'set':
            if msg['cmd2'] == 'ready_check':
                try:
                    room = group_name
                    parsed = room[room.rindex('-')+1:]
                    m = matchplayers.objects.get(user_id=message.channel_session['user_id'],match_id=parsed)
                    m.ready = msg['message']
                    m.save()
                except:
                    pass






@channel_session
def ws_disconnect(message):
    try:
        group_name = chat_session.objects.filter(user=message.channel_session['user_id']).distinct().values("group_name")
        try:
            chat_session.objects.filter(user=message.channel_session['user_id']).delete()
        except chat_session.DoesNotExist:
            pass
        try:
            for group in group_name:
                Group(group.group_name).discard(message.reply_channel)
        except KeyError:
            pass
    except:
        pass`

**Comment by andrewgodwin** [comment]
You need to make sure you're on Channels >= 1.0 and then remove enforce_ordering from the `ws_connect` receiver, that will help (it's not needed, this is done for you now in a more efficient way).

That might help, and then you might want to consider seeing if you can write the other code in a way where it's not needed, otherwise, I suspect you need to wait for the next channels release and this will be fixed with the patch we already landed. Closing here as it's not an asgi_redis bug.
