### ISSUE TITLE
How to use CHANNEL_LAYERS setting in Django?

### ISSUE THREAD

**Issue by lingliqianxun** [django/asgi_redis#34]
models.py

    CHANNEL_LAYERS = {
        "default": {
            "ROUTING": "models.routing.channel_routing",
            "BACKEND": "asgi_redis.RedisChannelLayer",
            "CONFIG": {
                "capacity": 100,
                "channel_capacity": {
                    "http.request": 200,
                    "http.response*": 10,
                    "websocket.send*": 110,
                },
            }
        },
    }

test.html

    <script type="text/javascript">
        function WebSocketBulletLaunch()
        {
                setInterval(function(){
                str = '{"action":"test"}'
                socket.send(str);
            },100);		
        }
    </script>

I use `test.html` to testing,it will 10 request 1s then `ChanelFull`.
I see `capacity` default 100 in asgi_redis/core.py and `channel_capacity` in your answers to other people's questions.I want to know `capacity` relationship with `channel_capacity`.When I mass request 1s，it will raise `ChanelFull`，how to set and testing the relationship.
I also not see the detail description in [Channels readme](http://channels.readthedocs.io),and I see the following in asgi_redis the following.

> Support for configuring the socket_connect_timeout, socket_timeout, socket_keepalive and socket_keepalive_options

### How to use them?

**Comment by andrewgodwin** [comment]
Capacity is the default capacity for all channels. Channel capacity overrides this on a per-channel basis. You'll only get ChannelFull if you're not consuming off of a channel as well (so things build up in the channel); in a normal scenario, your capacity should be around the number of requests per second you can handle.

Other options: Pass them in the CONFIG dictionary along with other arguments like capacity and channel_capacity.
