### ISSUE TITLE
Support redis database number

### ISSUE THREAD

**Issue by cellofellow** [django/asgi_redis#38]
Redis connections can have a database number (0-127). Please allow setting this in the config.

**Comment by andrewgodwin** [comment]
It's possible to set this using a URI for configuration rather than a host/port tuple: https://redis-py.readthedocs.io/en/latest/#redis.StrictRedis.from_url

**Comment by flyte** [comment]
Could you provide an example `CHANNEL_LAYERS` configuration that makes use of the URI instead of the host/port tuple? Are we able to just provide a URI string instead of the tuple in the `hosts` list? This doesn't appear to be demonstrated anywhere in the Channels/channels_redis documentation?

**Comment by flyte** [comment]
Ah, I found the section now - there's a link to https://aioredis.readthedocs.io/en/v1.1.0/api_reference.html#aioredis.create_connection in the readme which specifies the format you can use.
