### ISSUE TITLE
RedisChannelLayer.receive runs forever

### ISSUE THREAD

**Issue by AlexejStukov** [django/asgi_redis#44]
`RedisChannelLayer.receive`, that was reworked in #43, now hangs forever if called with block. That was not the case in the previous version (it returned `(None, None)`. This prevents channels `Worker` from exiting if termed is set to true (e.g. in the signal handler).

**Comment by andrewgodwin** [comment]
The ASGI spec says "block means that the call can take as long as it likes", so this is valid behaviour. What needs fixing here is the channels Worker; if you could file a bug against the `channels` project we can fix it over there so an interrupt correctly yanks it out of any receive call.

**Comment by AlexejStukov** [comment]
Done. Maybe I will try my luck at fixing this in channels tomorrow. Thanks for your work, guys!

**Comment by AlexejStukov** [comment]
@andrewgodwin maybe the ASGI spec should be reworded, because in the same paragraph there is the sentence: "If block is True, then it will not return until after a built-in timeout or a message arrives;" 
For me that means that it should eventually return after a non infinite timeout.

**Comment by andrewgodwin** [comment]
Yes, I will clarify that paragraph so it's clear it is allowed to block forever.
