### ISSUE TITLE
Question: Does it work on Python 3.6?

### ISSUE THREAD

**Issue by Spritekin** [django/asgi_redis#46]
We are using this asgi_redis with python 3.6 and we are having problems setting this up. The docs say:
```
Redis >= 2.6 is required for asgi_redis. All Channels projects currently support Python 2.7, 3.4 and 3.5.
```

So not sure it it will work in 3.6. May someone more experienced please confirm?

**Comment by andrewgodwin** [comment]
I see no reason why not - 3.6 has no backwards incompatible features, it just came out more recently than that doc said. Let me add 3.6 to our build test suite and check for you.

**Comment by andrewgodwin** [comment]
Yup, 3.6 build is all green and works as expected: https://travis-ci.org/django/asgi_redis/jobs/237051035
