### ISSUE TITLE
receive() does not delete message bodies

### ISSUE THREAD

**Issue by andrewgodwin** [django/asgi_redis#48]
It reads them, but then does not delete the keys, causing Redis to balloon memory if there is high throughput within the expiry window. First reported as https://github.com/django/daphne/issues/124

**Comment by andrewgodwin** [comment]
@sjamaan I've patched it and verified that keys are no longer left around; do you want to run your test again against a master checkout and make sure that solves your issue?

**Comment by sjamaan** [comment]
Just tried, and the memory use is stable now. Thanks for the quick reply and fix!

**Comment by andrewgodwin** [comment]
Perfect. I'll roll it out into a release then.

**Comment by andrewgodwin** [comment]
Released in `1.4.1`.
