### ISSUE TITLE
The performance of version 1.4.x

### ISSUE THREAD

**Issue by belongwqz** [django/asgi_redis#50]
When I upgrade to 1.4.x(1.4.0 or 1.4.1), and visit a url(use ajax)very quickly, then no response for a period of time(more 10 seconds) and no abnormal output found.
When downgrade to 1.3.0 version, the problem disappeared.
I test with different version of channels and daphne, the porblem just about asgi_redis 1.4.x.
My CHANNEL_LAYERS setting like this:
```
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'asgi_redis.RedisChannelLayer',
        'CONFIG': {'hosts': ['redis://:pwd@redis1', 'redis://:pwd@redis2']},
        'ROUTING': 'MyProject.routing.channel_routing'
    }
}
```

**Comment by andrewgodwin** [comment]
Can you try with just a single host and see if that makes it any faster?

**Comment by belongwqz** [comment]
I have test it, and seems there's no this problem with single redis host.

**Comment by bgreenberg-eb** [comment]
I'm not familiar with the details of this deployment, but it seems like it could be related to the change from trying receive connections at random to round-robin.

**Comment by andrewgodwin** [comment]
Maybe. It sounds like the message is just not getting through at all, and Daphne is just timing out after 10 seconds.

@belongwqz Could you try running the ASGI benchmark suite on it with and without two hosts? You should be able to do this with the command `asgiref_benchmark -n 1000 your_project.asgi:channel_layer`

**Comment by belongwqz** [comment]
Hi @andrewgodwin, I can't find a asgiref_benchmark cmd, my env is:
Python 3.6.1
asgiref 1.1.2
I `grep` and `find` asgiref_benchmarkand but find nothing, could you tell me which is path of the asgiref_benchmark cmd.

**Comment by belongwqz** [comment]
benchmark.py not include in packages from `https://pypi.python.org/pypi/asgiref/1.1.2` but in `https://github.com/django/asgiref/blob/master/asgiref/benchmark.py`, then find `asgiref_benchmark = asgiref.benchmark:Benchmarker.cli`, maybe next version will include? I download benchmark.py to test first.

**Comment by belongwqz** [comment]
The command asgiref_benchmark not include in https://pypi.python.org/pypi/asgiref/1.1.2?I download from github to test first.
result with single host:
```
Running receiver...
Running sender...
Warming up...
Sent 0
Sent 100
Received 100
Sent 200
Received 200
Sent 300
Received 300
Sent 400
Received 400
Sent 500
Sent 600
Received 500
Received 600
Sent 700
Sent 800
Received 700
Received 800
Sent 900
Received 900
Sender complete
Received 1000
Sender exited, scheduling receiver shutdown
Receiver complete. Calculating stats...

Received: 1000/1000 (100.0%)
Latency mean: 0.0197  median: 0.0238  10%: 0.0087  90%: 0.0258
Send throughput: 4295.6/s
Receive throughput: 3939.5/s
```
with 2 hosts:
```
Running receiver...
Running sender...
Warming up...
Sent 0
Sent 100
Received 100
Sent 200
Received 200
Sent 300
Received 300
Sent 400
Sent 500
Received 400
Sent 600
Received 500
Sent 700
Received 600
Sent 800
Sent 900
Received 700
Received 800
Sender complete
Received 900
Received 1000
Sender exited, scheduling receiver shutdown
Receiver complete. Calculating stats...

Received: 1000/1000 (100.0%)
Latency mean: 0.0718  median: 0.0728  10%: 0.0217  90%: 0.1191
Send throughput: 2130.2/s
Receive throughput: 1724.2/s
```

**Comment by andrewgodwin** [comment]
OK, so there's no problem with asgi_redis then, which is what I was worried about (it is slower, but that as it's a single consumer/receiver test, so it can't benefit from parallelisation). I'm going to close this issue as it's against asgi_redis.

If the response isn't finding its way to the browser, you need to go through and check all the pieces of the puzzle involved in WebSockets - any load balancers, any SSL terminators, and any static file/reverse proxy servers like nginx. The easiest way to check is to directly connect to Daphne from your web browser and see if you still get issues (most people who have this issue have it work fine talking to Daphne directly, and then it gets problematic with something else in their stack).

**Comment by belongwqz** [comment]
Well, I try to directly connect to daphne from web browser, then the problem still exist. 
I am puzzled, why the 1.3.0 version does not have this problem.
I‘ll’ try to find the problem again on my test environment, but the production environment I have to use the 1.3.0 version.
Something about my test enveronment here as fllow:
versions:
```
asgi-redis (1.4.1)
asgiref (1.1.2)
channels (1.1.5)
daphne (1.3.0)
```
start command:
```
daphne MyPorject.asgi:channel_layer -b 0.0.0.0 --port 8000 --proxy-headers --access-log ./logs/access.log (only one server)
python manage.py runworker -v 2 (8 workers)
```

**Comment by andrewgodwin** [comment]
There's one last thing to try - try checking out the latest git master of asgi_redis and run that. There's a commit from a few days ago that might possibly have fixed this if it's what I think it might be.

**Comment by belongwqz** [comment]
Yes, the lastest git masterof asgi_redis solves this problem.

**Comment by andrewgodwin** [comment]
Interesting, so it's the forever-blocking receive call that did it (bd485f48dfa55b1aefd7676f39aef8b128667588) - that's still a bug in Daphne, but at least now I know what to look for!

**Comment by andrewgodwin** [comment]
If you update to 1.4.2 which I released this morning, the problem should go away for you in that too. I will work on fixing Daphne to not hang on this problem soon, as it's probably still causing high latency even if it works.

**Comment by belongwqz** [comment]
@andrewgodwin thank you.
