### ISSUE TITLE
PaaS Redis connection string is a bit awkward to work with

### ISSUE THREAD

**Issue by lwm** [django/asgi_redis#52]
If I get a Redis connection string that looks like:

```
redis://h:password@ec2-666.eu-west-1.compute.amazonaws.com:29739
```
I can't just pass it as:

```
 "CONFIG": {"hosts": ["redis://h:password@ec2-666.eu-west-1.compute.amazonaws.com:29739"]},
```

I get the following error:

```
  File "/home/lwm/.local/share/virtualenvs/carbondoomsday-IdcgiUO9/lib/python3.5/site-packages/asgi_redis/core.py", line 102, in _setup_hosts
    final_hosts.append("redis://%s:%d/0" % (entry[0], entry[1]))
TypeError: 'Value' object does not support indexing
```

So, I need to parse the connection string and split it into host and port? I did see the full string [being passed in the documentation](https://github.com/django/asgi_redis#symmetric_encryption_keys) but I assume that is out of date or?

**Comment by andrewgodwin** [comment]
No, you can pass strings. The problem is that what you have passed is not a string but a `Value`, if you look at the error message. Work out how that happened and you'll be good.
