### ISSUE TITLE
Performance improvements.

### ISSUE THREAD

**Issue by KhasanovBI** [django/asgi_redis#56]
1) Some of dependent packages have performance optimizations related with cythonized or C-implemented parts:
    a) `msgpack-python`, if `cython` installed then shared C-library built and msgpack used it instead python fallback.
    b) `redis`, if `hiredis` installed then fast `HiredisParser` used.
So first question is may be we should specify this requirements in dependencies or at least write about them in Readme?

2) What about asyncio? I see https://github.com/django/asgiref/blob/master/asgiref/inmemory_async.py and extension part in docs (PS. I don't understand why twisted there, if in world may be a lot of frameworks should we write some adapter for each of them) and second question:
What if I wan't to use aioredis in server part? Should I need add new asgi_aioredis for server and use asgi_redis in django workers, or should I add it to asgi_redis as a extension? And what if I wan't use pub sub in redis as channels backend?

**Comment by proofit404** [comment]
Hi, thanks for feedback!

If you're using recent pip, you will have wheel installation of the msgpack package. It's already compiled to c extension. Cython installation isn't necessary. It is required only if you decide to recompile it from sdist yourself. But in this case user already knows what to do.

Hiredis is widely used and don't require any change in our code base. I think we can mention it in the docs or even show warning message if this library is missing. @andrewgodwin any suggestions?

You can implement `asyncio` extension for channel layer. But you need protocol server capable to use it. Channels itself complete synchronous in it's core. And Daphne will use `twisted` extension. So it's much more work then just receive method.

Also consider to read recent blog post by @andrewgodwin

**Comment by andrewgodwin** [comment]
We could definitely mention `hiredis` in the docs somewhere, that would be an easy performance improvement for those that can install it. I'm not sure if it works for things like PyPI though so I'm not sure I want to turn it into a warning.

**Comment by proofit404** [comment]
Ok, I'll do that.
