### ISSUE TITLE
asgi_redis & asgi-redis

### ISSUE THREAD

**Issue by nim65s** [django/asgi_redis#58]
Hi,

Sorry if this is trivial, but I don't understand why after a `pip install asgi_redis`, `pip freeze` says that I have `asgi-redis`. I don't see that `asgi-redis` anywhere in this repo or on pypi.

**Comment by andrewgodwin** [comment]
I can't help you there - the package name in setup.py is set to be `asgi_redis`, and `asgi-redis` appears nowhere in the repo or in its name. Maybe a pip bug?

**Comment by nim65s** [comment]
Ok, found it, thanks.

https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L1391

Maybe we should avoid `[^A-Za-z0-9.]` in package names x)
