### ISSUE TITLE
Cluster configuration

### ISSUE THREAD

**Issue by LiteWait** [django/asgi_redis#65]
I don't need a completely fault tolerant cluster, but I need each web servers (IP listed below) to appear as a single resource/store for asgi_redis.

```
2ad4b07c712c9c40c9845dc6d673baaf0a1318e7 10.0.3.11:6379@16379 master - 0 1514391205000 3 connected 8192-12287
82ea477823891419705780d70e5d83f89aeffb17 10.0.3.13:6379@16379 master - 0 1514391205879 4 connected 12288-16383
8bcb722e24dd67b06008beca347ea0b3bac40111 10.0.1.10:6379@16379 master - 0 1514391204577 1 connected 0-4095
28dafba3059b4b9e6343e8fb1cf771aedca560bb 10.0.1.12:6379@16379 myself,master - 0 1514391205000 2 connected 4096-8191
```

What would I set 'hosts' to in CHANNEL_LAYERS?

**Comment by andrewgodwin** [comment]
If you're referring to `redis-cluster`, asgi_redis does not support it as it only provides a subset of the normal Redis operations.

If you want to use the built-in sharding algorithm, simply set the `hosts` key to a list of those four host URIs.
