### ISSUE TITLE
Multiple servers, node down handling

### ISSUE THREAD

**Issue by LiteWait** [django/asgi_redis#66]
I've pitched asgi_rabbitmq in favor of asgi_redis and I have this working using the normal sharding algorithm, worried what happens if one of the nodes goes down and how that is managed?  
I know libs like PyLibMC are smart enough to handle nodes that stop responding, and manage them accordingly.  Just wondering when a node stops responding how can I expect asgi_redis and channels to react till I scramble around and get the node up again.  Thanks.

**Comment by andrewgodwin** [comment]
If one of the shards goes down you're going to get tracebacks or timeouts as asgi_redis tries to talk to it until it comes back up - there's nothing smart in there by default. There's an optional sentinel mode that will use `redis-sentinel` to pick a server for each shard that you can use to get redundant shards if you want.
