### ISSUE TITLE
msgpack-python is renamed to msgpack

### ISSUE THREAD

**Issue by bastbnl** [django/asgi_redis#67]
Hi,

I ran into an issue `Daphne` not starting due to a missing `msgpack` module. The msgpack-python module was installed, but it was missing the msgpack module. I took a look at https://pypi.python.org/pypi/msgpack-python and found this:
> msgpack-python is renamed to just msgpack.

It appears to have been done very recently, though. Would it be better to update the dependencies in `setup.py` to include `msgpack` instead of `msgpack-python`?

Happy to add a PR, btw

**Comment by bastbnl** [comment]
Package was missing due to the way I update the virtualenv btw, so no real issues there

**Comment by andrewgodwin** [comment]
Fixed in the 2.0 branch.
