### ISSUE TITLE
Multiple workers with Redis don't invalidate cache

### ISSUE THREAD

**Issue by bogdancondurache** [django/asgi_redis#69]
Hello,

After deploying Django with Daphne and Redis (asgi_redis) as in documentation, I made a Circus config to run 4 workers, Redis and Daphne. The problem is that using multiple workers, the cache is not invalidated at some times. For example I make a change in the app and start refreshing. Sometimes the change will appear, sometimes not. Also, the frontend part of the app is separate (a React app) and not using Django templates. I found no way to specify exactly when to invalidate the cache (after an action, not a number of seconds). And when I use only one worker I don't have this issue. Is this a bug or am I doing something wrong?

Versions:
asgi-redis==1.4.3
channels==1.1.8
daphne==1.4.2
Django==1.11.9

**Comment by andrewgodwin** [comment]
Please don't duplicate issues across projects - I already started answering this over here: https://github.com/django/daphne/issues/154, please continue discussion there if you have more information/
